In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import glob
path="C:/Users/mehdi/courses/"
from pathlib import Path
folder="C:/Users/mehdi/courses/rental project"
li=[]
for file in Path(folder).glob('*.csv'):
    df = pd.read_csv(file)
    li.append(df)
df=pd.concat(li,axis=0,ignore_index=True).drop(columns=['Unnamed: 0'])


df=df.dropna()
df['price'] = df['price'].map(lambda x: x.replace(',',''))
df['price'] = df['price'].astype(int)

df['bedroom']=df['bedroom'].apply(lambda r:int(r) if isinstance(r,int) else r.split('+')[0])
df['bedroom']=df['bedroom'].astype(int)
df['bathroom'] = df['bathroom'].replace(r'^([A-Za-z]|[0-9]|_)+$', np.NaN, regex=True)
df=df.dropna()
df['bathroom']=df['bathroom'].astype(int)
df['size_sqf'] = df['size_sqf'].replace(r'^([A-Za-z]|[0-9]|<)+$', np.NaN, regex=True)
df=df.dropna()
df['size_sqf'] = df['size_sqf'].replace('5000+',5000,regex=True)
df['size_sqf'] = df['size_sqf'].astype(int)
df=df[df['size_sqf']>100]
for col in ['Address', 'types', 'city', 'province']:
    df[col] = df[col].astype('category')
df=df.reset_index()

In [2]:
df

,index,price,Address,moreinfo,bedroom,bathroom,size_sqf,types,city,province
0,0,1425,Poplar,1 bd\n1 ba\n533 sf,1,1,533,Apt/Condo,Abbotsford,BC
1,1,2245,Poplar,2 bd\n2 ba\n910 sf,2,2,910,Apt/Condo,Abbotsford,BC
2,2,1350,Abbotsford West,1 bd\n1 ba\n538 sf,1,1,538,Apt/Condo,Abbotsford,BC
3,3,1725,Poplar,1 bd\n1 ba\n689 sf,1,1,689,Apt/Condo,Abbotsford,BC
4,4,1625,Central Abbotsford,2 bd\n1 ba\n846 sf,2,1,846,Apt/Condo,Abbotsford,BC
...,...,...,...,...,...,...,...,...,...,...
1890,4984,801,Yorkton,1 bd\n1 ba\n502 sf,1,1,502,Apt/Condo,yorkton,SK
1891,4986,926,Yorkton,2 bd\n1 ba\n709 sf,2,1,709,Apt/Condo,yorkton,SK
1892,4989,951,Yorkton,3 bd\n1 ba\n806 sf,3,1,806,Apt/Condo,yorkton,SK
1893,4990,951,Yorkton,3 bd\n1 ba\n806 sf,3,1,806,Apt/Condo,yorkton,SK
1894,4991,851,Yorkton,2 bd\n1 ba\n709 sf,2,1,709,Apt/Condo,yorkton,SK